name: docker

on:
  push:
    branches:
      - 'main'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2      
      - name: Build only
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: stereum-dev/synclink-client:latest
        if: startsWith(github.tag, 'v') != true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: startsWith(github.tag, 'v')
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 
          - sapien99/synclink-client:latest
          - sapien99/synclink-client:github.tag
        if: startsWith(github.tag, 'v')
